[package]
name = "cortex-r-rt"
categories = ["embedded", "no-std"]
version = "0.1.0"
authors = ["Gregory Kent <gregory.c.kent2.civ@mail.mil>"]

[dependencies]
r0 = "0.2.1"
cortex-r-rt-macros = { path = "macros", version = "0.1.0" }
